# Generated by Django 5.2 on 2025-07-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('biografia', models.TextField(blank=True, null=True)),
                ('total_musicas_artista', models.IntegerField(default=0)),
                ('total_albuns_artista', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=50)),
                ('nomeUsuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('total_musicas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('ano_lancamento', models.IntegerField()),
                ('duracao_total', models.CharField(blank=True, max_length=20, null=True)),
                ('capa', models.ImageField(upload_to='')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='napisfy.artista')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='napisfy.genero')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbuns',
            },
        ),
        migrations.CreateModel(
            name='Cancoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('duracao', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancoes', to='napisfy.album')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancoes', to='napisfy.artista')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancoes', to='napisfy.genero')),
            ],
            options={
                'verbose_name': 'Canção',
                'verbose_name_plural': 'Canções',
            },
        ),
        migrations.CreateModel(
            name='PlaylistPubli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('duracao_total', models.CharField(blank=True, max_length=20, null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('dono_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='napisfy.conta')),
                ('musicas', models.ManyToManyField(blank=True, related_name='playlists', to='napisfy.cancoes')),
            ],
            options={
                'verbose_name': 'Playlist Pública',
                'verbose_name_plural': 'Playlists Públicas',
            },
        ),
    ]
