# Generated by Django 5.2 on 2025-07-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('napisfy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancoes',
            name='image',
        ),
    ]
