# Generated by Django 5.2 on 2025-07-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('napisfy', '0002_remove_cancoes_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancoes',
            name='audio_link',
        ),
        migrations.RemoveField(
            model_name='cancoes',
            name='genero',
        ),
    ]
