# Generated by Django 5.2 on 2025-07-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napisfy', '0003_remove_cancoes_audio_link_remove_cancoes_genero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cancoes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playlistpubli',
            options={},
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, null=True, unique=True),
        ),
    ]
